version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo:latest
    volumes:
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
      - ./scripts/init.js:/scripts/init.js
      - ./scripts/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      mongo-network:
        ipv4_address: 172.16.238.10
    ports:
      - 27058:27017
    depends_on:
      - mongo2
      - mongo3
      - mongo4
    links:
      - mongo2
      - mongo3
      - mongo4
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo2:
    container_name: mongo2
    image: mongo:latest
    networks:
      mongo-network:
        ipv4_address: 172.16.238.11
    ports:
      - 27059:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo3:
    container_name: mongo3
    image: mongo:latest
    networks:
      mongo-network:
        ipv4_address: 172.16.238.12
    ports:
      - 27060:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo4:
    container_name: mongo4
    image: mongo:latest
    networks:
      mongo-network:
        ipv4_address: 172.16.238.13
    ports:
      - 27061:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

networks:
  mongo-network:
    ipam:
      driver: default    # bridge
      config:
        - subnet: 172.16.238.0/24