services:
  mongo1:
    container_name: mongo1
    image: mongo:latest
    volumes:
      - ./scripts/rs-init.sh:/scripts/rs-init.sh:ro
      - ./scripts/init.js:/scripts/init.js
    networks:
      mongo-network:
        ipv4_address: 172.16.238.10
    ports:
      - 127.0.0.1:27017:27017
    depends_on:
      - mongo2
      - mongo3
      - mongo4
    restart: always
    command: ["--bind_ip_all", "--replSet", "dbrs"]

  mongo2:
    container_name: mongo2
    image: mongo:latest
    networks:
      mongo-network:
        ipv4_address: 172.16.238.11
    ports:
      - 127.0.0.2:27017:27017
    restart: always
    command: ["--bind_ip_all", "--replSet", "dbrs"]

  mongo3:
    container_name: mongo3
    image: mongo:latest
    networks:
      mongo-network:
        ipv4_address: 172.16.238.12
    ports:
      - 127.0.0.3:27017:27017
    restart: always
    command: ["--bind_ip_all", "--replSet", "dbrs"]

  mongo4:
    container_name: mongo4
    image: mongo:latest
    networks:
      mongo-network:
        ipv4_address: 172.16.238.13
    ports:
      - 127.0.0.1:27061:27017
    restart: always
    command: ["--bind_ip_all", "--replSet", "dbrs"]

networks:
  mongo-network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24